
RELEASE_MODE :=

.PHONY: release
release: RELEASE_MODE := release
release: all

.PHONY: debug
debug: RELEASE_MODE := debug
debug: all

.PHONY: all
all:
#	@$(MAKE) $(RELEASE_MODE) -C project1
#	@$(MAKE) $(RELEASE_MODE) -C project1_test
#	@$(MAKE) $(RELEASE_MODE) -C project2
#	@$(MAKE) $(RELEASE_MODE) -C project3

.PHONY: clean
clean:
#	@$(MAKE) clean -C project1
#	@$(MAKE) clean -C project1_test
#	@$(MAKE) clean -C project2
#	@$(MAKE) clean -C project3